name: Hourly Data Updates

on:
  push:
    paths:
      - '.github/workflows/data-updater.yml'
      - 'script-compiled.py'
  schedule:
    - cron: '0 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: python -m pip install --upgrade pip pandas
    - name: Clean and update with latest data
      run: python script-compiled.py
    - name: Commit & push data updates
      run: |
        git config --local user.name github-actions
        git config --local user.email "action@github.com"
        git add data/*.csv
        git diff --cached --quiet
        if [[ $? = 1 ]]; then
          git commit -m "Daily data update"
          git tag -a `date "+v%Y%m%d%H%M%S"` -m "Daily data update"
          git push origin master --tags
        fi
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
